<a href="https://colab.research.google.com/github/Sourav7490/ma22c046_2023_PL/blob/main/Assignment-8/Column_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from scipy.linalg import svd, qr

In [3]:
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

In [4]:
print(A)

[[ 1 -2  3 -3]
 [ 2 -4  9 -2]
 [-3  6 -9  9]]


**Task-1**

In [18]:
u, s, vh = svd(A)
print("Basis column space of using svt")
basis_svt=u
print(basis_svt)


Basis column space of using svt
[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]]


In [21]:
q, R = qr(A)
print("Basis column space of QR factorization")
basis_qr=q
print(basis_qr)

Basis column space of QR factorization
[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]


In [13]:
print("Column spaces obtained using QR and SVD are the same Rank.")

Column spaces obtained using QR and SVD are the same Rank.


**Task-2**

In [24]:
aug_uq=np.vstack((u,q))
print(aug_uq)
rank_aug_uq = np.linalg.matrix_rank(aug_uq)
rank_u = np.linalg.matrix_rank(u)
rank_q = np.linalg.matrix_rank(q)

print("Rank of aug_uq:", rank_aug_uq)
print("Rank of u:", rank_u)
print("Rank of q:", rank_q)


[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]
 [-2.67261242e-01  9.56182887e-01 -1.19522861e-01]
 [-5.34522484e-01 -4.39019222e-02  8.44013232e-01]
 [ 8.01783726e-01  2.89459681e-01  5.22834534e-01]]
Rank of aug_uq: 3
Rank of u: 3
Rank of q: 3


Here we can see that rank(aug_uq)=rank(u)=rank(q).Hence we can say that the svd matirx is able to generate the basis we got from qr and both basis generate same column space.


**Task-3**

In [25]:
B=np.random.rand(500,500)
U,S,VT=svd(B)
Q,R=qr(B)
%timeit U,S,VT
%timeit Q,R

160 ns ± 73.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
70 ns ± 0.737 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


Here we can see that QR factorization is faster than svd.