<a href="https://colab.research.google.com/github/Sourav7490/ma22c046_2023_PL/blob/main/Assignment-8/Null_Space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
from scipy.linalg import svd, qr
#given matrix A
A = np.array([[1, -2, 9, 5, 4,], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2],[4, 1, 9, 1, -9]])
A

array([[ 1, -2,  9,  5,  4],
       [ 1, -1,  6,  5, -3],
       [-2,  0, -6,  1, -2],
       [ 4,  1,  9,  1, -9]])

**Task-1**

null space of the given matrix A using SVD.

In [9]:
u,s,vT=svd(A)
print(vT)

[[ 0.24638127 -0.04503456  0.8742475   0.30107333 -0.28690474]
 [-0.12991821 -0.20626881  0.22905181  0.27058334  0.90271499]
 [ 0.3027347   0.2022255   0.3015276  -0.84037193  0.26516538]
 [-0.87219483  0.3573579   0.29073161 -0.14709627 -0.07354813]
 [ 0.26466093  0.8870317  -0.08822031  0.32905504  0.16452752]]


In [12]:
# Find the null space from SVD
null_space_svd = vT[:, np.where(s < 1e-10)].squeeze()
print("Null space using SVD:")
print(null_space_svd)


Null space using SVD:
[ 0.30107333  0.27058334 -0.84037193 -0.14709627  0.32905504]


In [14]:
Q, R = qr(A.T)
null_space_qr = Q[:, np.where(np.abs(np.diag(R)) < 1e-10)]      # The null space vectors are the columns of Q corresponding to zero columns in R
print("Null space using QR factorization (orthogonal complement of range of transpose A")
print(null_space_qr)

Null space using QR factorization (orthogonal complement of range of transpose A
[[[ 0.57324869]]

 [[ 0.68751498]]

 [[-0.1910829 ]]

 [[ 0.36021819]]

 [[ 0.18010909]]]


In [15]:
if null_space_svd.shape[0] == null_space_qr.shape[0]:
    print("Null spaces obtained using SVD and QR span the same space.")
else:
    print("Null spaces obtained using SVD and QR do not span the same space.")

Null spaces obtained using SVD and QR span the same space.
