<a href="https://colab.research.google.com/github/Sourav7490/ma22c046_2023_PL/blob/main/Assignment-5/Row_swap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
def swaprow(i, j, A):
  tmp = A[i, :]
  A[i, :] = A[j, :]
  A[j, :] = tmp

In [11]:
import numpy as np


In [12]:
A=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(A)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [13]:
swaprow(1,2,A)
print(A)

[[1 2 3]
 [5 6 7]
 [5 6 7]]


In [14]:
#There is an error of this given code.Now we are modify and rewrite the code.

In [18]:
def swaprow(i, j, A):
  tmp = A[i, :].copy()       # Now this is deep copy
  A[i, :] = A[j, :]
  A[j, :] = tmp

In [19]:
A=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(A)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [20]:
swaprow(1,2,A)
print(A)

[[1 2 3]
 [5 6 7]
 [3 4 5]]
