<a href="https://colab.research.google.com/github/Sourav7490/ma22c046_2023_PL/blob/main/Assigenment-6/Pairwise%20differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x = np.random.rand(5)

In [2]:
D = np.subtract.outer(x, x)
print(D)

[[ 0.         -0.17871539 -0.59859886 -0.63699546 -0.41624021]
 [ 0.17871539  0.         -0.41988347 -0.45828007 -0.23752482]
 [ 0.59859886  0.41988347  0.         -0.0383966   0.18235865]
 [ 0.63699546  0.45828007  0.0383966   0.          0.22075525]
 [ 0.41624021  0.23752482 -0.18235865 -0.22075525  0.        ]]


In [3]:
# Another version
A = np.zeros((5,5))
for i in range(5):
  for j in range (5):
    A[i][j]=x[i]-x[j]

print(A)

[[ 0.         -0.17871539 -0.59859886 -0.63699546 -0.41624021]
 [ 0.17871539  0.         -0.41988347 -0.45828007 -0.23752482]
 [ 0.59859886  0.41988347  0.         -0.0383966   0.18235865]
 [ 0.63699546  0.45828007  0.0383966   0.          0.22075525]
 [ 0.41624021  0.23752482 -0.18235865 -0.22075525  0.        ]]
